### ISSUE TITLE
[HPA] .spec.Autoscaler.behavior is not updated properly

### ISSUE THREAD

**Issue by moh-osman3** [open-telemetry/opentelemetry-operator#1516]
**What I expected:**
I expected to be able to add HPA `behavior` field to an already existing HPA spec and have this applied to the HPA config.

**What actually happened:**
HPA never actually sets the behavior when updating.  If behavior is not set in the original spec then it will never be used, because the update is not occurring.

**Comment by edwintye** [comment]
Thanks a lot for raising the issue.  We found it out the hard way when upgrade the operator image + CRD in our cluster. This is definitely a bug because it actually causes the operator to crash when it tries to reconcile an existing custom resource (CR).

For anyone who is facing this issue and want a fix forward/interim solution: we manually patched the k8s manifest of our collector via

```bash
kubectl patch opentelemetrycollectors.opentelemetries.io <the name of your collector> --type=merge -p '{"spec":{"autoscaler":{"maxReplica":<copy max replicate from existing field>,"minReplicas":<copy min replica from existing field>}}}'
```

which allows the operator to take control of the CR again as the max/min replica field exist in both location, and back to normal operation.
