### ISSUE TITLE
High Security Vulnerability 

### ISSUE THREAD

**Issue by sreejesh-radhakrishnan-db** [open-telemetry/opentelemetry-operator#1701]
Hi we are planning to use OPTEL- Operator for our Tracing. But we have a strict policy on vulnerability, the image opentelemetry-operator:v0.75.0  on our XRAY scan has shown below vulnerability  

XRAY-193029  High 
component  -> github.com/prometheus/prometheus:1.8.2-0.20210621150501-ff58416a0b02
Due to version  LESS THAN  2.24.0
FIX version pn 2.24.0

Looking at your repo, the change might be for this line to push to latest version. Please can you do this change and publish a latest image? 

https://github.com/open-telemetry/opentelemetry-operator/blob/d91958327d2d2c34a711ee2a31ff405a3e1597b6/go.mod#LL12C1-L12C1

**Comment by jaronoff97** [comment]
This is actually not an accurate report from XRAY because Prometheus' versioning has been messed up multiple times. 

version `1.8.2-0.20210621150501-ff58416a0b02`'s publish date is June 2021, which is after the release for [2.24](https://github.com/prometheus/prometheus/releases/tag/v2.24.0) 

Regardless, it would probably be good for us to bump our prometheus version.
