### ISSUE TITLE
Setting imagePullPolicy/secrets for autoinstrumentation image with security

### ISSUE THREAD

**Issue by oscaratienzaatosnet** [open-telemetry/opentelemetry-operator#2760]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

Well i am trying to install an own autoinstrumentation image in a private registry with creds (we can just use images with credentials) and we dont have the option to set secrets or pullPolicy to image in autoinstrumentation

### Describe the solution you'd like

an option to pull this settings in the Instrumentation CRD 

### Describe alternatives you've considered

pull the image locally and install it with podman, but it is not secure enough

**Comment by jaronoff97** [comment]
Hello! We have instructions on our recommendations [here](https://github.com/open-telemetry/opentelemetry-operator?tab=readme-ov-file#using-imagepullsecrets). Please let me know if that doesn't answer your question.

**Comment by jaronoff97** [comment]
Though looking over that again, I notice that recommendation is mainly for collectors and not instrumentation... I'll reopen this for discussion on if we should recommend the same for instrumentation.

**Comment by swiatekm-sumo** [comment]
Instrumentation injects init containers into application Pods, and pull secrets are set at the Pod level. So if the ServiceAccount or pullSecrets you have set on your instrumented Pod have permissions to pull your private instrumentation image, everything should work fine. Is this not the case?

I'm not sure we can allow this to be set on the Instrumentation CR, because even if we did, we don't have any way of merging  this with what the Pod already has set.
