### ISSUE TITLE
Kubernetes version support policy

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2798]
### Describe the issue you're reporting

How many versions back of Kubernetes do we support?

**Comment by jaronoff97** [comment]
We plan to support kubernetes HEAD-6 versions, @swiatekm-sumo will bump versions once a quarter :) 

This means we will support minimum inclusive of 1.24 starting in april. min 1.25 in july, min 1.26 in october and so forth.

@pavolloffay is that okay with you?

**Comment by frzifus** [comment]
Should be good with openshift (https://access.redhat.com/support/policy/updates/openshift) wdyt @pavolloffay ?

**Comment by pavolloffay** [comment]
@frzifus I don't think so. OCP 4.12 is based on k8s 1.25 and it will be supported until `January 17, 2025` https://access.redhat.com/support/policy/updates/openshift. 

Is there any technical issue that forces us to bump the minimal supported k8s version? Given that we have to support the operator on all supported OpenShift versions I would prefer to evaluate the min version update case by case.

**Comment by swiatekm-sumo** [comment]
@pavolloffay we'd like to have a predictable support policy, so users can anticipate when we're going to drop support. "Case by case" means we could end support for all non-EOL versions today if we wanted to, which isn't ideal.

In a practical sense, "support the same version as the most conservative distributions" sounds fine as a policy to me, but I think we'd like to link this to upstream releases, rather than forcing users to go check OpenShift or EKS to understand the operator's policy.
