### ISSUE TITLE
Issue with Deploying Otel Operator and Instrumentation CR instance via Helm

### ISSUE THREAD

**Issue by ZiedChekir** [open-telemetry/opentelemetry-operator#3014]
### Component(s)

Instrumentation CR
## Description

When deploying the otel operator and Instrumentation CR instance via a custom Helm chart, there is a labeling conflict. The CR is labeled as `app.kubernetes.io/managed-by=Helm`, while according to the OpenTelemetry documentation, it needs to be managed by the OpenTelemetry operator with the label `app.kubernetes.io/managed-by=opentelemetry-operator`. This conflict causes the auto-instrumentation process to fail as the operator cannot add the necessary annotations to the Instrumentation CR, which are necessary for injecting the correct image into the auto-instrumentation initContainer.

## Steps to Reproduce

Deploy the Otel operator and Instrumentation CR using a custom Helm chart.

## Expected Result

The Otel operator should manage the Instrumentation CR, adding the necessary annotations, and successfully inject the appropriate image into the auto-instrumentation initContainer.

## Actual Result
I get an error in the deployment resource saying `spec.initcontainers[0].image is a required value` which means the application looked at the instrumenation CR instance but did not find the autoinstrumenation images in the annotations since it is managed by Helm

### Kubernetes Version

1.29

### Operator version

0.98.0

### Collector version

0.98.0

**Comment by jaronoff97** [comment]
[Discussions here](https://cloud-native.slack.com/archives/C03HVLM8LAH/p1717619485184129?thread_ts=1717611417.583469&cid=C03HVLM8LAH)

**Comment by jaronoff97** [comment]
Thanks for the added context!! i think this is all because of how we upgrade things because [this logic](https://github.com/open-telemetry/opentelemetry-operator/blob/4cd4454d7260b7804cc0877d66ba36608889d3d4/pkg/instrumentation/upgrade/upgrade.go#L111-L159) only runs when that is set. We filter based on this label for upgrades for [the collector](https://github.com/open-telemetry/opentelemetry-operator/blame/main/pkg/collector/upgrade/upgrade.go#L45-L50) and [instrumentations](https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/upgrade/upgrade.go#L83-L87). This means that despite setting the right images on the operator, we never set those correctly on the instrumentation.

**Comment by jaronoff97** [comment]
this will have to be breaking change, but I think that's acceptable given the current state isn't great. cc @open-telemetry/operator-approvers thoughts?
