### ISSUE TITLE
Community Operators - OpenTelemetry operator failing on Kiwi test

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/opentelemetry-operator#599]
After releasing v0.39.0 to community operators repo, I noticed that we are facing the following issue: 

`TASK [check_image_availability : Print err message] ****************************
fatal: [localhost]: FAILED! => changed=false 
  msg: |-
    Value of 'metadata.annotations.containerImage' not used in any container, please check.
    The operator is using some image which must have exactly the same value as 'metadata.annotations.containerImage'.
    Please check both values and make them the same.
`
https://github.com/k8s-operatorhub/community-operators/runs/4406065202?check_suite_focus=true

**Comment by jpkrohling** [comment]
I think those tests are new, added by @pavolloffay.

**Comment by pavolloffay** [comment]
TBH I don't know what Kiwi test is. I have added only scorecard tests that we run on CI in this repository and they pass.

**Comment by pavolloffay** [comment]
The issue is not related to the scorecard.

We have renamed the image from quay to ghcr but we forgot to update this field https://github.com/open-telemetry/opentelemetry-operator/blob/1275f2e262c998879fc6f79ea88b55b9984cd1a1/bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml#L33. It should be changed to `ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator`

**Comment by pavolloffay** [comment]
This should fix this https://github.com/open-telemetry/opentelemetry-operator/pull/600. 

For the 0.39.0 it will have to be done manually

**Comment by yuriolisa** [comment]
I'll prepare the PR for the community operators.
