### ISSUE TITLE
Add support for golang auto-instrumentation

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#908]
The https://github.com/keyval-dev/opentelemetry-go-instrumentation could be used for golang auto-instrumentation. 

From the object management perspective it would be better if the project was part of the CNCF/OTEL community.

cc) @edeNFed

**Comment by pavolloffay** [comment]
Golang auto-instrumentation has been donated https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/2

**Comment by TylerHelmuth** [comment]
@pavolloffay @open-telemetry/operator-maintainers @open-telemetry/operator-approvers if the community is willing, I would like to start working on this.

**Comment by edeNFed** [comment]
@TylerHelmuth I'll be happy to help if needed

**Comment by TylerHelmuth** [comment]
@edeNFed sounds good! I'm sure I'll have some questions once I get started.

**Comment by TylerHelmuth** [comment]
Please assign this to me.

**Comment by TylerHelmuth** [comment]
Question: will we want to build our own version of the go auto-instrumentation agent like we do for the other languages or will it be acceptable to use the image published by opentelemetry-go-instrumentation?

**Comment by TylerHelmuth** [comment]
As discussed in the SIG meeting today, we'll move forward with using an image published from open-telemetry/opentelemetry-go-instrumentation instead of building our own.  This decision is made based on the increased complexity of the go auto instrumentation due to eBPF and the necessary offsets json file we would have to manage if we had our own image.
